import pytest
import allure
import time
from playwright.sync_api import Page, Playwright
from pages.login_page import LoginPage
from pages.create_product_page import CreateProductPage
from pages.storefront_page import StorefrontPage
from config import Config
from api.medusa_api import MedusaAPIClient
from pages.products_page import ProductsPage

# Фикстуры бека


@pytest.fixture
def auth_client(playwright: Playwright):
    request_context = playwright.request.new_context(base_url=Config.API_URL)
    client = MedusaAPIClient(request_context)
    yield client
    request_context.dispose()


@pytest.fixture
def api_client(playwright: Playwright):
    request_context = playwright.request.new_context(base_url=Config.API_URL)
    client = MedusaAPIClient(request_context)
    client.login(Config.ADMIN_EMAIL, Config.ADMIN_PASSWORD)
    yield client
    request_context.dispose()  # dispose нужен для разрыва соединения


# Фикстуры фронта - заготовка, тесты отключены (нестабильный фронтенд в локальном окружении)



@pytest.fixture
def login_page(page: Page):
    return LoginPage(page)


@pytest.fixture
def products_page(page: Page):
    return ProductsPage(page)


@pytest.fixture
def create_product_page(page: Page):
    return CreateProductPage(page)


@pytest.fixture
def storefront_page(page: Page):
    return StorefrontPage(page)


# Фикстура allure
@pytest.hookimpl(tryfirst=True, hookwrapper=True)
def pytest_runtest_makereport(item, call):
    outcome = yield
    rep = outcome.get_result()
    if rep.when == "call" and rep.failed:
        page = item.funcargs.get("page")
        if page:
            screenshot = page.screenshot(full_page=True)
            allure.attach(
                screenshot,
                name=f"Скриншот падения: {item.name}",
                attachment_type=allure.attachment_type.PNG,
            )


# фикстура для создания тестовых данных (продукта)
@pytest.fixture
def generate_product_payload():
    def _generator(title: str = None, price_usd: int = 150) -> dict:
        actual_title = title if title else f"Auto Sneaker {int(time.time() * 1000)}"
        return {
            "title": actual_title,
            "description": "Generated by Pytest Fixture",
            "status": "published",
            "options": [{"title": "Size", "values": ["US 10"]}],
            "variants": [
                {
                    "title": "US 10",
                    "manage_inventory": False,
                    "prices": [{"amount": price_usd * 100, "currency_code": "eur"}],
                }
            ],
        }

    return _generator


@pytest.fixture
def empty_cart_id(api_client):
    pk_key = api_client.generate_publishable_key()
    sc_id = api_client.get_default_sales_channel_id()
    reg_id, currency = api_client.get_default_region_info()
    response = api_client.create_empty_cart(
        pk_key=pk_key, sales_channel_id=sc_id, region_id=reg_id
    )
    assert response.status == 200, f"Не удалось создать корзину! {response.text()}"
    return response.json()["cart"]["id"], pk_key, sc_id, currency
